#!/usr/bin/env python3
"""
Readability report for Co-Intelligent Co-Operation.
Generates per-chapter and per-worksheet stats using textstat.

Run: uv run --with textstat python3 audit/readability-report.py
"""

import os
import re
import sys
import json

import textstat


def strip_markdown(text):
    """Remove markdown syntax, YAML frontmatter, code blocks, and tables."""
    # Remove YAML frontmatter
    text = re.sub(r'^---\n.*?\n---\n', '', text, flags=re.DOTALL)
    # Remove code blocks
    text = re.sub(r'```.*?```', '', text, flags=re.DOTALL)
    # Remove inline code
    text = re.sub(r'`[^`]+`', '', text)
    # Remove tables (lines starting with |)
    text = re.sub(r'^\|.*$', '', text, flags=re.MULTILINE)
    # Remove headings markers but keep text
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    # Remove bold/italic markers
    text = re.sub(r'\*{1,3}([^*]+)\*{1,3}', r'\1', text)
    # Remove links, keep text
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
    # Remove images
    text = re.sub(r'!\[.*?\]\(.*?\)', '', text)
    # Remove blockquote markers
    text = re.sub(r'^>\s?', '', text, flags=re.MULTILINE)
    # Remove horizontal rules
    text = re.sub(r'^---+$', '', text, flags=re.MULTILINE)
    # Remove HTML tags
    text = re.sub(r'<[^>]+>', '', text)
    # Remove checkbox markers
    text = re.sub(r'\[[ x]\]', '', text)
    # Remove blank placeholder lines (underscores)
    text = re.sub(r'^_+$', '', text, flags=re.MULTILINE)
    # Collapse whitespace
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def analyze(filepath):
    """Return readability metrics for a single file."""
    with open(filepath, 'r') as f:
        raw = f.read()

    text = strip_markdown(raw)

    if len(text.split()) < 50:
        return None  # Too short for meaningful analysis

    return {
        'word_count': textstat.lexicon_count(text, removepunct=True),
        'sentence_count': textstat.sentence_count(text),
        'avg_sentence_length': round(textstat.words_per_sentence(text), 1),
        'flesch_reading_ease': round(textstat.flesch_reading_ease(text), 1),
        'flesch_kincaid_grade': round(textstat.flesch_kincaid_grade(text), 1),
        'gunning_fog': round(textstat.gunning_fog(text), 1),
        'coleman_liau': round(textstat.coleman_liau_index(text), 1),
        'automated_readability': round(textstat.automated_readability_index(text), 1),
        'dale_chall': round(textstat.dale_chall_readability_score(text), 1),
        'linsear_write': round(textstat.linsear_write_formula(text), 1),
        'text_standard': textstat.text_standard(text, float_output=False),
        'reading_time_min': round(textstat.reading_time(text, ms_per_char=14.69) / 60, 1),
    }


def grade_label(score):
    """Interpret Flesch Reading Ease score."""
    if score >= 80:
        return "Easy (6th grade)"
    elif score >= 60:
        return "Standard (8th-9th grade)"
    elif score >= 50:
        return "Fairly Difficult (10th-12th)"
    elif score >= 30:
        return "Difficult (college)"
    else:
        return "Very Difficult (graduate)"


def format_report(results):
    """Format results as markdown."""
    lines = []
    lines.append("# Readability Report")
    lines.append("")
    lines.append(f"Generated by `textstat` on {__import__('datetime').date.today().isoformat()}")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| File | Words | Sentences | Avg Sent Len | Flesch RE | FK Grade | Fog | Text Standard | Read Time |")
    lines.append("|------|-------|-----------|-------------|----------|---------|-----|---------------|-----------|")

    for r in results:
        m = r['metrics']
        if m is None:
            continue
        lines.append(
            f"| {r['label']} | {m['word_count']:,} | {m['sentence_count']} | {m['avg_sentence_length']} | "
            f"{m['flesch_reading_ease']} | {m['flesch_kincaid_grade']} | {m['gunning_fog']} | "
            f"{m['text_standard']} | {m['reading_time_min']}m |"
        )

    # Totals
    total_words = sum(r['metrics']['word_count'] for r in results if r['metrics'])
    total_sentences = sum(r['metrics']['sentence_count'] for r in results if r['metrics'])
    avg_flesch = round(
        sum(r['metrics']['flesch_reading_ease'] * r['metrics']['word_count']
            for r in results if r['metrics'])
        / total_words, 1
    ) if total_words else 0
    total_reading = round(sum(r['metrics']['reading_time_min'] for r in results if r['metrics']), 1)

    lines.append(
        f"| **TOTAL** | **{total_words:,}** | **{total_sentences}** | "
        f"**{round(total_words/total_sentences, 1) if total_sentences else 0}** | "
        f"**{avg_flesch}** | — | — | — | **{total_reading}m** |"
    )

    lines.append("")

    # Interpretation guide
    lines.append("## Score Guide")
    lines.append("")
    lines.append("**Flesch Reading Ease** (higher = easier):")
    lines.append("- 80-100: Easy (6th grade) — casual conversation")
    lines.append("- 60-79: Standard (8th-9th grade) — plain English, most business writing target")
    lines.append("- 50-59: Fairly Difficult (10th-12th) — professional/trade publications")
    lines.append("- 30-49: Difficult (college level) — academic papers, technical docs")
    lines.append("- 0-29: Very Difficult (graduate+) — legal, scientific")
    lines.append("")
    lines.append("**Flesch-Kincaid Grade:** US school grade level needed to understand the text.")
    lines.append("")
    lines.append("**Gunning Fog:** Estimates years of formal education needed. Target for broad audiences: 8-12.")
    lines.append("")
    lines.append("**Target for this book:** Flesch RE 50-65 (accessible business prose, not dumbed down). FK Grade 8-12.")
    lines.append("")

    # Per-file detail
    lines.append("## Per-File Detail")
    lines.append("")

    for r in results:
        m = r['metrics']
        if m is None:
            continue
        lines.append(f"### {r['label']}")
        lines.append("")
        lines.append(f"- **Words:** {m['word_count']:,}")
        lines.append(f"- **Sentences:** {m['sentence_count']}")
        lines.append(f"- **Avg sentence length:** {m['avg_sentence_length']} words")
        lines.append(f"- **Flesch Reading Ease:** {m['flesch_reading_ease']} — {grade_label(m['flesch_reading_ease'])}")
        lines.append(f"- **Flesch-Kincaid Grade:** {m['flesch_kincaid_grade']}")
        lines.append(f"- **Gunning Fog:** {m['gunning_fog']}")
        lines.append(f"- **Coleman-Liau Index:** {m['coleman_liau']}")
        lines.append(f"- **Automated Readability Index:** {m['automated_readability']}")
        lines.append(f"- **Dale-Chall:** {m['dale_chall']}")
        lines.append(f"- **Linsear Write:** {m['linsear_write']}")
        lines.append(f"- **Consensus grade level:** {m['text_standard']}")
        lines.append(f"- **Estimated reading time:** {m['reading_time_min']} min")
        lines.append("")

    return '\n'.join(lines)


def main():
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    chapters_dir = os.path.join(base, 'chapters')
    worksheets_dir = os.path.join(base, 'worksheets')
    audit_dir = os.path.join(base, 'audit')

    results = []

    # Chapters
    if os.path.isdir(chapters_dir):
        chapter_files = sorted([
            f for f in os.listdir(chapters_dir)
            if f.endswith('.qmd') and not f.startswith('appendix')
        ])
        for fname in chapter_files:
            filepath = os.path.join(chapters_dir, fname)
            label = fname.replace('.qmd', '')
            metrics = analyze(filepath)
            results.append({'label': f"Ch: {label}", 'metrics': metrics})

    # Appendices
    if os.path.isdir(chapters_dir):
        appendix_files = sorted([
            f for f in os.listdir(chapters_dir)
            if f.endswith('.qmd') and f.startswith('appendix')
        ])
        for fname in appendix_files:
            filepath = os.path.join(chapters_dir, fname)
            label = fname.replace('.qmd', '')
            metrics = analyze(filepath)
            results.append({'label': f"App: {label}", 'metrics': metrics})

    # Index/preface
    index_path = os.path.join(base, 'index.qmd')
    if os.path.isfile(index_path):
        metrics = analyze(index_path)
        results.append({'label': "Preface: index", 'metrics': metrics})

    # Worksheets
    if os.path.isdir(worksheets_dir):
        ws_files = sorted([
            f for f in os.listdir(worksheets_dir) if f.endswith('.md')
        ])
        for fname in ws_files:
            filepath = os.path.join(worksheets_dir, fname)
            label = fname.replace('.md', '')
            metrics = analyze(filepath)
            results.append({'label': f"WS: {label}", 'metrics': metrics})

    report = format_report(results)

    os.makedirs(audit_dir, exist_ok=True)
    outpath = os.path.join(audit_dir, 'readability-report.md')
    with open(outpath, 'w') as f:
        f.write(report)

    print(f"Report written to {outpath}")
    print(f"\nProcessed {len([r for r in results if r['metrics']])} files")
    print(f"Total words: {sum(r['metrics']['word_count'] for r in results if r['metrics']):,}")


if __name__ == '__main__':
    main()
